### ISSUE TITLE
旧リポジトリからコミットを引き継ぐ

### ISSUE THREAD

**Issue by Slimebreath6078** [Slimebreath6078/SBband#64]
- [ ] Slimebreath6078/SBband_private#22
- [x] Slimebreath6078/SBband_private#30
- [ ] Slimebreath6078/SBband_private#40
- [x] Slimebreath6078/SBband_private#45
- [x] Slimebreath6078/SBband_private#53
- [x] Slimebreath6078/SBband_private#57
- [ ] Slimebreath6078/SBband_private#73
- [ ] Slimebreath6078/SBband_private#91
- [ ] Slimebreath6078/SBband_private#105
- [ ] Slimebreath6078/SBband_private#106
- [ ] Slimebreath6078/SBband_private#111
- [ ] Slimebreath6078/SBband_private#112
- [ ] Slimebreath6078/SBband_private#119
- [ ] Slimebreath6078/SBband_private#122
- [ ] Slimebreath6078/SBband_private#132
- [ ] Slimebreath6078/SBband_private#140
- [ ] Slimebreath6078/SBband_private#141
- [ ] Slimebreath6078/SBband_private#143
- [ ] Slimebreath6078/SBband_private#145
- [ ] Slimebreath6078/SBband_private#146
- [ ] Slimebreath6078/SBband_private#147
- [ ] Slimebreath6078/SBband_private#151
